name: deploy-gcloud-service-develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  gcloud-deploy-develop:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -   uses: google-github-actions/deploy-appengine@main
          with:
            credentials: ${{ secrets.GCP_CREDENTIALS_DEVELOP }}
